spring:
  profiles:
    active: dev
---
spring:
  application:
    name: SERVICE-PROVIDER
  config:
    activate:
      on-profile: dev
dubbo:
  scan:
    base-packages: com.iterators.service.provider.service
  application:
    name: service-provider
    metadata-type: remote
  protocol:
    name: dubbo
    port: -1
  provider:
    export: true
  metadata-report:
    address: redis://127.0.0.1:6379
    retry-times: 30
    retry-period: 5000
    cycle-report: false
  config-center:
    protocol: nacos
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
  registry:
    address: nacos://127.0.0.1:8848
    register: true
    username: nacos
    password: nacos

server:
  port: 8081
