spring:
  profiles:
    active: dev
---
spring:
  application:
    name: SERVICE-CONSUMER
  config:
    activate:
      on-profile: dev
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    protocol: dubbo
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
  metadata-report:
    address: redis://127.0.0.1:6379
  config-center:
    protocol: nacos
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos

server:
  port: 8082
